---
- name: Creating OpenVPN Client certificate and key pair
  command: ./easyrsa build-client-full "{{ item.split(',')[0] | trim }}" nopass
  args:
    chdir: /etc/openvpn/easy-rsa/
    creates: "/etc/openvpn/easy-rsa/pki/issued/{{ item }}.crt"
  with_items: "{{ lookup('file', 'clientlist').splitlines() }}"
  ignore_errors: true

- name: Creating certificate revocation list
  command: ./easyrsa gen-crl
  environment:
    EASYRSA_CRL_DAYS: 3650
  args:
    chdir: "{{ openvpn_base_directory }}/easy-rsa/"
    creates: "{{ openvpn_base_directory }}/easy-rsa/pki/crl.pem"

# not working 
#- name: Copying certificate revocation list
#  copy:
#    src: "{{ openvpn_base_directory }}/easy-rsa/pki/crl.pem"
#    dest: "{{ openvpn_base_directory }}"
#    owner: nobody
#    group: nogroup

- name: Copying client keys to openvpn directory
  copy:
    src: "{{ openvpn_base_directory }}/easy-rsa/pki/private/{{ item }}.key"
    dest: "{{ openvpn_base_directory }}"
    remote_src: yes
  with_items: "{{ lookup('file', 'clientlist').splitlines() | trim }}"
  ignore_errors: true

- name: Copying client certificate to openvpn directory
  copy:
    src: "{{ openvpn_base_directory }}/easy-rsa/pki/issued/{{ item }}.crt"
    dest: "{{ openvpn_base_directory }}"
    remote_src: yes
  with_items: "{{ lookup('file', 'clientlist').splitlines() }}"
  ignore_errors: true

- name: Copying the sample script to generate client keys
  copy:
    src: make_config.sh
    dest: "{{ openvpn_base_directory }}"
    mode: 0700

- name: Creating client certificate and key
  command: ./make_config.sh "{{ item.split(',')[0] | trim }}"
  args:
    chdir: "{{ openvpn_base_directory }}"
    creates: "{{ openvpn_base_directory }}{{ item }}.ovpn"
  with_items: "{{ lookup('file', 'clientlist').splitlines() }}"
  ignore_errors: true

#- name: Copying the client.ovpn to localhost
#  fetch:
#    src: "/{{ openvpn_base_directory }}/{{ item }}.ovpn"
#    dest: /tmp/
#    flat: yes
#  with_items: "{{ lookup('file', 'clientlist').splitlines() }}"
#  ignore_errors: true

#https://docs.ansible.com/ansible/latest/modules/fetch_module.html#fetch-module
#
#- name: Copying the client.openvpn to  openvpn_clients
#  fatch:
#    src:
#    dest:
