---

- name: Copy the sample template of server configuration
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_directory }}/server.conf"

- name: Copy the sample template of client configuration
  template:
    src: client.conf.j2
    dest: "{{ openvpn_base_directory }}/client.conf"

- name: Indicating PORT & OPENVPN_PROTOCOL in server.conf
  lineinfile:
    dest: "{{ openvpn_base_directory }}/server.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: 'port 1194', line: 'port {{ OPENVPN_PORT }}' }
  - { regexp: 'proto udp', line: 'proto {{ OPENVPN_PROTOCOL }}' }

#- name: Getting public IP for client.conf
#  ipify_facts:
#    - 

- name: Indicating PORT & OPENVPN_PROTOCOL in client.conf
  lineinfile:
    dest: "{{ openvpn_base_directory }}/client.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: 'proto udp', line: 'proto {{ OPENVPN_PROTOCOL }}' }
  - { regexp: 'remote my-server-1 1194', line: 'remote {{ ipify_public_ip }} {{ OPENVPN_PORT }}' }
  notify:
    - daemon_reload
    - starting_openvpn
