---
- name: Installing  required packages for ubuntu & Debian
  apt: name="{{ packages }}" update_cache=yes state=present
  vars:
    packages:
    - apache2
    - libapache2-mod-wsgi
    - python-geoip
    - python-ipaddr
    - python-humanize
    - python-bottle
    - python-semantic-version
    - geoip-database-extra
    - geoipupdate
  when: ansible_distribution == "Ubuntu" or ansible_distribution=="Debian"

- name: Installing required packages for Redhat & Centos
  yum: name="{{ packages }}" update_cache=yes state=present
  vars:
    packages:
    - httpd
    - git
    - wget
    - mod_wsgi
    - python2-geoip2
    - python-ipaddr
    - python-humanize
    - python-bottle
    - python-semantic-version
    - geolite2-city
#    - GeoIP-update
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Creating a file in apache2 directory for ubuntu & Debian
  file:
    path: "{{ apache-dir-ubuntu }}"
    state: touch
    mode: "u=rw,g=r,o=r"
  when: ansible_distribution == "Ubuntu" or ansible_distribution=="Debian"

- name: Creating a file in apache2 directory for Redhat & Centos
  file:
    path: "{{ apache-dir-centos }}"
    state: touch
    mode: "u=rw,g=r,o=r"
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Deleting apache2 home-page from apache2 directory
  file:
    path: /var/www/html/index.html
    state: absent

- name: configuring apache2 for openvpn-monitor for ubuntu & Debian
  lineinfile:
    path: "{{ apache-dir-ubuntu }}"
    insertafter: EOF
    line: 'WSGIScriptAlias /openvpn-monitor /var/www/html/openvpn-monitor/openvpn-monitor.py'
  when: ansible_distribution == "Ubuntu" or ansible_distribution=="Debian"

- name: configuring apache2 for openvpn-monitor for Redhat & Centos
  lineinfile:
    path: "{{ apache-dir-centos }}"
    insertafter: EOF
    line: 'WSGIScriptAlias /openvpn-monitor /var/www/html/openvpn-monitor/openvpn-monitor.py'
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: enable openvpn-monitor configuration ubuntu & Debian
  command: a2enconf openvpn-monitor
  when: ansible_distribution == "Ubuntu" or ansible_distribution=="Debian"

- name: Creating openvpn-monitor directory
  file:
    path: /var/www/html/openvpn-monitor
    state: directory

- name: Cloning Openvpn-monitor source-code
  git:
    repo: "{{ openvpn-monitor-giturl }}"
    dest: /var/www/html/openvpn-monitor/
    version: master

- name: restart apache2 ubuntu & Debian
  service: name=apache2 state=restarted
  when: ansible_distribution == "Ubuntu" or ansible_distribution=="Debian"

- name: restart httpd for Redhat & Centos
  service: name=httpd state=restarted
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"
...