---
#https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md
- name: Revoking OpenVPN Client certificate and key pair
  command: ./easyrsa --batch revoke "{{ item.split(',')[0] | trim }}"
  args:
    chdir: "{{ openvpn_base_directory }}/easy-rsa/"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true

- name: Removing client certificate revocation list from pki
  file:
    state: absent
    path: /{{ openvpn_base_directory }}/easy-rsa/pki/crl.pem

- name: Creating client certificate revocation list
  command: ./easyrsa gen-crl
  environment:
    EASYRSA_CRL_DAYS: 3650
  args:
    chdir: "{{ openvpn_base_directory }}/easy-rsa/"
    creates: "{{ openvpn_base_directory }}/easy-rsa/pki/crl.pem"

- name: Removing client certificate revocation list from base directory
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/crl.pem"

- name: Copying client certificate revocation list from pki directory
  copy:
    src: "{{ openvpn_base_directory }}/easy-rsa/pki/crl.pem"
    dest: "{{ openvpn_base_directory }}/crl.pem"
    remote_src: yes

- name: Removing client certificate request
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/easy-rsa/pki/reqs/{{ item }}.req"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true

- name: Removing client certificate
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/{{ item }}.crt"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true

- name: Removing client certificate from pki directory
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/easy-rsa/pki/issued/{{ item }}.crt"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true

- name: Removing client key
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/{{ item }}.key"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true

- name: Removing client key from pki directory
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/easy-rsa/pki/private/{{ item }}.key"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true

- name: Removing client.ovpn key
  file:
    state: absent
    path: "{{ openvpn_base_directory }}/{{ item }}.ovpn"
  with_items: "{{ lookup('file', 'revokelist').splitlines() }}"
  ignore_errors: true
